In [1]:
using LinearAlgebra
using Plots

In [49]:
# Questão realizada pelos alunos 
# Augusto Guimarães - DRE:119025393, 
# Luiz Rodrigo Lace - DRE: 118049873 e 
# Livia Barbosa Fonseca - DRE: 118039721.
# 1 - i
# Matriz Diagonal
# Recebe como parametro duas matrizes A e b e retorna x tal que Ax = b.
# A deve ser uma matriz diagonal.
function resolve_diagonal(A, b)
    n = size(A, 1)
    x = zeros(n, 1)
    for i = 1:n
        x[i] = b[i] / A[i, i]
    end
    x
end

resolve_diagonal (generic function with 1 method)

In [50]:
Teste1 = [2 0 0 ;0 3 0; 0 0 4]
x_verdadeiro=randn(3,1)
b= Teste1*x_verdadeiro
x_calculado=resolve_diagonal(Teste1 ,b)
norm(x_verdadeiro-x_calculado) < 0.000000000001

true

In [51]:
Teste2= [10 0 0 0 0;0 3 0 0 0; 0 0 7 0 0; 0 0 0 9 0; 0 0 0 0 6]
x_verdadeiro=randn(5,1)
b= Teste2*x_verdadeiro
x_calculado=resolve_diagonal(Teste2,b)
norm(x_verdadeiro-x_calculado) < 0.000000000001

true

In [5]:
Teste3 = [10 0 0 0 0 0 0;0 8 0 0 0 0 0; 0 0 17 0 0 0 0; 0 0 0 99 0 0 0; 0 0 0 0 66 0 0; 0 0 0 0 0 111 0; 0 0 0 0 0 0 7 ]
x_verdadeiro=randn(7,1)
b= Teste3*x_verdadeiro
x_calculado=resolve_diagonal(Teste3,b)
norm(x_verdadeiro-x_calculado) < 0.000000000001

true

In [52]:
# 1 - ii
# Matriz Diagonal Superior
# Recebe como parametro duas matrizes A e b e retorna x tal que Ax = b.
# A deve ser triangular superior
function resolve_triangular_superior(A, b)
    n = size(A, 1)
    x = zeros(n, 1)
    for i = reverse(1:n)
        x[i] = b[i]
        for j = reverse(i+1:n)
            x[i] -= A[i, j] * x[j]
        end
        x[i] /= A[i, i]
    end
    return x
end

resolve_triangular_superior (generic function with 1 method)

In [53]:
Teste1 = [2 2 2 ;0 3 3; 0 0 4]
x_verdadeiro=randn(3,1)
b= Teste1*x_verdadeiro
x_calculado=resolve_triangular_superior(Teste1 ,b)
norm(x_verdadeiro-x_calculado) < 0.000000000001

true

In [54]:
Teste2= [10 244 421 33 1;0 3 33 22 11; 0 0 7 6 5; 0 0 0 92 1; 0 0 0 0 68]
x_verdadeiro=randn(5,1)
b= Teste2*x_verdadeiro
x_calculado=resolve_triangular_superior(Teste2,b)
norm(x_verdadeiro-x_calculado) < 0.000000000001

true

In [55]:
Teste3 = [10 20 30 40 50 60 70;0 82 2 3 40 1 1; 0 0 17 20 30 40 110; 0 0 0 99 33 55 44; 0 0 0 0 66 11 22; 0 0 0 0 0 111 3; 0 0 0 0 0 0 7 ]
x_verdadeiro=randn(7,1)
b= Teste3*x_verdadeiro
x_calculado=resolve_triangular_superior(Teste3,b)
norm(x_verdadeiro-x_calculado) < 0.000000000001

true

In [56]:
# 1 - iii
# Matriz Diagonal Inferior
# Recebe como parametro duas matrizes A e b e retorna x tal que Ax = b.
# A deve ser triangular inferior
function resolve_triangular_inferior(A, b)
    n = size(A, 1)
    x = zeros(n, 1)
    for i = 1:n
        x[i] = b[i]
        for j = 1:i-1
            x[i] -= A[i, j] * x[j]
        end
        x[i] /= A[i, i]
    end
    return x
end

resolve_triangular_inferior (generic function with 1 method)

In [57]:
Teste1 = [1 0 0; 3 2 0; 1 4 3]
x_verdadeiro=randn(3,1)
b= Teste1*x_verdadeiro
x_calculado=resolve_triangular_inferior(Teste1 ,b)
norm(x_verdadeiro-x_calculado) < 0.000000000001

true

In [58]:
Teste2= [10 0 0 0 0;3 3 0 0 0; 7 6 5 0 0; 1 92 33 1 0; 244 421 33 1 68]
x_verdadeiro=randn(5,1)
b= Teste2*x_verdadeiro
x_calculado=resolve_triangular_inferior(Teste2,b)
norm(x_verdadeiro-x_calculado) < 0.000000000001

true

In [59]:
Teste3 = [1 0 0; 1 1 0; 1 1 1]
x_verdadeiro=randn(3,1)
b= Teste3*x_verdadeiro
x_calculado=resolve_triangular_inferior(Teste3 ,b)
norm(x_verdadeiro-x_calculado) < 0.000000000001

true

In [60]:
# 1 - iv
# Decomposição LU
# Recebe uma matriz a e retorna as matrizes L e U.
# Codigo baseado nas observações feitas em sala de aula e 
# nas informações encontradas no site: https://www.ime.unicamp.br/~pjssilva/pdfs/notas_de_aula/ms211/Sistemas_Lineares.pdf
function decomposicao_lu(A)
    U = copy(A)
    n = size(A, 1)
    L = Matrix{Float64}(I, n, n) #Matriz identidade
    for i = 1:n
        for j = i+1:n
            coef=U[j, i] / U[i, i]
            L[j, i] = coef
            U[j, :] -= coef * U[i, :]
        end
    end
    L, U
end

decomposicao_lu (generic function with 1 method)

In [61]:
teste1 = [-4.0 1 1 0; 1 -4 0 1; 1 0 -4 1; 0 1 1 -4]
L,U=decomposicao_lu(teste1)

([1.0 0.0 0.0 0.0; -0.25 1.0 0.0 0.0; -0.25 -0.06666666666666667 1.0 0.0; -0.0 -0.26666666666666666 -0.2857142857142857 1.0], [-4.0 1.0 1.0 0.0; 0.0 -3.75 0.25 1.0; 0.0 0.0 -3.7333333333333334 1.0666666666666667; 0.0 0.0 0.0 -3.428571428571429])

In [62]:
L

4×4 Matrix{Float64}:
  1.0    0.0         0.0       0.0
 -0.25   1.0         0.0       0.0
 -0.25  -0.0666667   1.0       0.0
 -0.0   -0.266667   -0.285714  1.0

In [63]:
U

4×4 Matrix{Float64}:
 -4.0   1.0    1.0       0.0
  0.0  -3.75   0.25      1.0
  0.0   0.0   -3.73333   1.06667
  0.0   0.0    0.0      -3.42857

In [64]:
teste2 = [4.0 3; 6 3]
L,U=decomposicao_lu(teste2)

([1.0 0.0; 1.5 1.0], [4.0 3.0; 0.0 -1.5])

In [65]:
L

2×2 Matrix{Float64}:
 1.0  0.0
 1.5  1.0

In [66]:
U

2×2 Matrix{Float64}:
 4.0   3.0
 0.0  -1.5

In [67]:
teste3 = [2.0 3 -1; 4 4 -1; -2 -3 4]
L,U=decomposicao_lu(teste3)

([1.0 0.0 0.0; 2.0 1.0 0.0; -1.0 -0.0 1.0], [2.0 3.0 -1.0; 0.0 -2.0 1.0; 0.0 0.0 3.0])

In [68]:
L

3×3 Matrix{Float64}:
  1.0   0.0  0.0
  2.0   1.0  0.0
 -1.0  -0.0  1.0

In [69]:
U

3×3 Matrix{Float64}:
 2.0   3.0  -1.0
 0.0  -2.0   1.0
 0.0   0.0   3.0

In [70]:
# 1 - v
# Matriz inversa
# AX = LUX = B
# Supondo que B seja matriz identidade então X será a inversa de A
# Substituindo UX por y =>
# Ly = B
# UX = y
function Matriz_inversa(T)
    n = size(T, 1)
    identidade = Matrix{Int64}(I, n, n) 
    L,U=decomposicao_lu(T) #Complexidade O(n^3)
    y=L\identidade #Complexidade O(n^3)
    x=U\y #Complexidade O(n^3)
    return x
end
# Complexidade 3 * O(n^3)

Matriz_inversa (generic function with 1 method)

In [24]:
# 2 - b)
# Construção do sistema linear em formato de matriz.
A = [-2 1 0 0 0;1 -2 1 0 0;0 1 -2 1 0;0 0 1 -2 1;0 0 0 1 -2]
B = [365/27; 1000/27; 500/9;2000/27; 1960/27]

5-element Vector{Float64}:
 13.518518518518519
 37.03703703703704
 55.55555555555556
 74.07407407407408
 72.5925925925926

In [25]:
x = A\B

5-element Vector{Float64}:
 -100.52469135802468
 -187.53086419753086
 -237.50000000000003
 -231.91358024691363
 -152.25308641975312

In [26]:
#c)
#Utilizando funções de outras listas
function vandermonde(x,y,grau)
    n,=size(y)
    V=zeros(n,grau+1)
    for i=1:n #linhas
        for j=1:(grau+1)
            V[i,j]=x[i]^(j-1)
        end
    end
    return V
end

vandermonde (generic function with 1 method)

In [27]:
function regressão(x,y,grau)
    V=vandermonde(x,y,grau)
    c=V\y #mínimos quadrados
    return c
end

regressão (generic function with 1 method)

In [28]:
X=[0;5/3;10/3;15/3;20/3;25/3;10]
Y=[0;-100.52469135802468;-187.53086419753086;-237.50000000000003;-231.91358024691357;-152.25308641975312;20]
V=vandermonde(X,Y,3)
C=regressão(X,Y,3)
Polinomio(x)= C[1]+C[2]*x +C[3]*x^2 +C[4]*x^3

Polinomio (generic function with 1 method)

In [29]:
Polinomio(3.2345)

-182.78251632057936

In [ ]:
# 3 - b)
#Nesse item vamos determinar a temperatura nos 4 vértices do interior do quadrado com o LU. 
#Para isso, vamos utilizaremos as funções   resolve_triangular_superior(A, b), resolve_triangular_inferior(A, b) 
#e decomposicao_lu(A) que foram modeladas na questão 1 para resolver o sistema pelo método lu:
#Passando os valores das matrizes mencionadas anteriormente e chamando a função sistema_denso para resolver o sistema linear, temos: 

In [30]:
# Função que dado A e b de um sistema do tipo Ax=b retorna x
function sistema_denso(A,b)
    #Realiza a decomposição LU
    L,U=decomposicao_lu(A)
    #Resolve matriz triangular inferior
    y=resolve_triangular_inferior(L,b)
    #Resolve matriz triangular superior
    x=resolve_triangular_superior(U,y)
    #Retorna x de Ax=b
    return x
end


sistema_denso (generic function with 1 method)

In [31]:
#Matriz A de Ax=b
A = [-4.0 1 1 0; 1 -4 0 1; 1 0 -4 1; 0 1 1 -4]
#Matriz b de Ax=b
b = [-20;-50;-15;-45]

4-element Vector{Int64}:
 -20
 -50
 -15
 -45

In [32]:
#Resolvendo o sistema Ax=b via LU
sistema_denso(A,b)

4×1 Matrix{Float64}:
 13.125
 20.625
 11.875
 19.375

In [ ]:
#Assim temos que x1 = 13.125, x2 = 20.625, x3 = 11.875, x4 = 19.375.

In [ ]:
# 3 - c)
# Agora temos que determinar a temperatura dos vértices do interior do lago via método LU, 
# sabendo que a temperatura da margem mudou e o lago foi discretamente aumentado, conforme a figura na questão
# odemos observar que temos 25 pontos no interior do lago, ou seja, temos que escrever 25 equações, 
# sendo uma equação para cada ponto do lago. Sendo assim, para facilitar, construímos duas funções no Julia que nos devolve
# as matrizes modeladas para o problema

In [ ]:
# Primeiramente, estudamos o padrão que a  matriz A (Ax=b) estava estabelecendo e descobrimos que seria o mesmo da matriz A 
# do exercício anterior. Em seguida, descobrimos que este é um problema clássico, quando  possuímos um grid que representa 
# um sistema físico em equilíbrio Nestes casos, encontramos um “padrão fundamental” que a matriz estudada possui, e observamos 
# que ela segue o mesmo desenho para todas as discretizações a partir dela, tendo em mente que o número de linhas da matriz deve 
# ser o mesmo número de colunas, sendo estes quadrados perfeitos.

In [33]:
# Função que dado um n desejado cria uma matriz (nxn) no modelo do nosso 
# problema (funciona somente para n’s que são quadrados perfeitos)
function criação_da_matriz(n)
   #Cria uma matriz de zeros(nxn) 
    A=zeros(n,n)
   
    rq=Int(sqrt(n))
  
    #Passando os valores na primeira e última linha da matriz
    A[1,1]=-4
    A[1,2]=1
    A[n,n-1]=1
    A[n,n]=-4
   
    #tridiagonal
    for i= 2:(n-1)
        A[i,i]=-4
        A[i,i+1]=1
        A[i,i-1]=1
       
        if (i%rq == 0)
            A[i,i+1] = 0
        end
    end
   
    # 1's de baixo
    for i = (rq+1) : n
        A[i, i-rq] = 1
    end
   
    # 1's de cima
    for i = 1 : n - rq
        A[i, i+rq] = 1
    end
   
    # passando 1 para 0 a cada rq
    for i = rq : n-rq
        if i % rq == 0
            A[i+1,i] = 0
        end
    end
 
    #Retorna a matriz criada
    return A
end


criação_da_matriz (generic function with 1 method)

In [34]:
#Função que encontra a matriz b de (Ax=b) do problema modelado (só funciona para n’s que são quadrados perfeitos)
function matriz_resultado(n)
   #Cria uma matriz de zeros(nxn) 
    A=zeros(n,1)
   
    rq=Int(sqrt(n))
   
    #canto superior esquerdo
    A[1,1]  = -45
   
    #canto superior direito
    A[rq,1] = -40
   
    #canto inferior esquerdo
    A[n-rq+1,1] = -55
   
    #canto inferior direito
    A[n,1] = -50
   
    #cima
    for i = 2:rq-1
        A[i,1] = -20
    end
   
    #lado esquerdo
    for i = 1 : rq-2
        A[(i*rq)+1,1] = -25
    end
   
    #lado direito
    for i = 2 : rq-1
        A[(i*rq),1] = -20
    end
   
    #baixo
    for i = n-rq+2 : n-1
        A[i,1] = -30
    end
 
    #Retorna a matriz criada
    return A
end

matriz_resultado (generic function with 1 method)

In [35]:
A = criação_da_matriz(25)
b = matriz_resultado(25)
sistema_denso(A,b)

25×1 Matrix{Float64}:
 22.656565656565654
 21.762286324786324
 21.28651903651904
 20.89359945609946
 20.46969696969697
 23.863976301476303
 23.106060606060602
 22.49019036519036
 21.818181818181817
 20.98518842268842
 24.69327894327894
 24.30778943278943
 23.75
 22.903749028749036
 21.65287490287491
 25.601350038850036
 25.68181818181818
 25.29827117327117
 24.393939393939394
 22.722562160062164
 27.030303030303024
 27.519862082362078
 27.367327117327115
 26.65117521367521
 24.84343434343434

In [ ]:
# Dessa forma, podemos observar que encontramos os valores de x1 até xk para o nosso problema. 
# Sendo o primeiro número retornado o x1 e o x25 o último.

In [71]:
# 4 a)
# Montando o sistema
# x8 -x7 - x6 = 500
# x7 - x5 = 3000
# x6 - x2- x4 = 0 
# x5  - x3 = 3000
# x4 - x1 = 30000
# x3 = 9000
# x2 = 3500
# x1 = 7000
c =[1 0 0 0 0 0 0 0;
    0 1 0 0 0 0 0 0; 
    0 0 1 0 0 0 0 0; 
    -1 0 0 1 0 0 0 0;
    0 0 -1 0 1 0 0 0;
    0 -1 0 -1 0 1 0 0;
    0 0 0 0 -1 0 1 0;
    0.0 0 0 0 0 -1 -1 1] 

8×8 Matrix{Float64}:
  1.0   0.0   0.0   0.0   0.0   0.0   0.0  0.0
  0.0   1.0   0.0   0.0   0.0   0.0   0.0  0.0
  0.0   0.0   1.0   0.0   0.0   0.0   0.0  0.0
 -1.0   0.0   0.0   1.0   0.0   0.0   0.0  0.0
  0.0   0.0  -1.0   0.0   1.0   0.0   0.0  0.0
  0.0  -1.0   0.0  -1.0   0.0   1.0   0.0  0.0
  0.0   0.0   0.0   0.0  -1.0   0.0   1.0  0.0
  0.0   0.0   0.0   0.0   0.0  -1.0  -1.0  1.0

In [72]:
p =[7000;3500;9000;30000;3000;0 ;3000;500]

8-element Vector{Int64}:
  7000
  3500
  9000
 30000
  3000
     0
  3000
   500

In [73]:
#Reslvendo atraves da decomposição LU
sistema_denso(c,p)

8×1 Matrix{Float64}:
  7000.0
  3500.0
  9000.0
 37000.0
 12000.0
 40500.0
 15000.0
 56000.0

In [66]:
# Resposta:
# x1 = 7000
# x2 = 3500
# x3 = 9000
# x4 = 37000
# x5 = 12000
# x6 = 40500
# x7 = 15000
# x8 = 56000

In [74]:
# b)
# Montando o sistema
# x8 -x7 - x6 = 500
# x7 - x5 = 3000
# x6 - x2- x4 = 0 
# x5 + x9 - x3 = 3000
# x4 - x1 -x9= 30000
# x3 = 9000
# x2 = 3500
# x1 = 7000
j = [1 0 0 0 0 0 0 0 0;
    0 1 0 0 0 0 0 0 0;
    0 0 1 0 0 0 0 0 0;
    -1 0 0 1 0 0 0 0 -1;
    0 0 -1 0 1 0 0 0 1;
    0 -1 0 -1 0 1 0 0  0;
    0 0 0 0 -1 0 1 0 0;
    0 0 0 0 0 -1 -1 1 0;]


8×9 Matrix{Int64}:
  1   0   0   0   0   0   0  0   0
  0   1   0   0   0   0   0  0   0
  0   0   1   0   0   0   0  0   0
 -1   0   0   1   0   0   0  0  -1
  0   0  -1   0   1   0   0  0   1
  0  -1   0  -1   0   1   0  0   0
  0   0   0   0  -1   0   1  0   0
  0   0   0   0   0  -1  -1  1   0

In [75]:
w = [7000;3500;9000;30000;3000;0 ;3000;500]

8-element Vector{Int64}:
  7000
  3500
  9000
 30000
  3000
     0
  3000
   500

In [76]:
#Não é possivel fazer a decomposição LU pois a matriz não é quadrada
j\w

9-element Vector{Float64}:
   6999.9999999999945
   3500.0000000000036
   8999.999999999989
  26899.999999999967
  22100.000000000015
  30399.99999999998
  25100.000000000022
  55999.99999999999
 -10100.000000000027

In [9]:
#Resposta:
#x1 = 7000
#x2 = 3500
#x3 = 9000
#x4 = 26900
#x5 = 22100
#x6 = 30400
#x7 = 25100
#x8 = 56000
#x9 = -10100
# O fluxo no cano x9 é negativo porque o fluxo vai do ponto E para o D